memcached:
  image:
    registry: docker.io
    repository: giantswarm/bitnami-memcached
    tag: 1.6.21
    pullPolicy: IfNotPresent
    debug: true

  commonLabels:
    application.giantswarm.io/team: "atlas"
    giantswarm.io/managed-by: "memcached"
    application.kubernetes.io/version: "0.1.0"
    helm.sh/chart: "memcached"

  ## Allowed values: standalone (deployment) or high-availability (statefulset)
  architecture: standalone

  replicaCount: 1

  resources:
    limits: {}
    requests:
      memory: 256Mi
      cpu: 250m

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 6
    targetCPU: 50
    targetMemory: 50

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: giantswarm/bitnami-memcached-exporter
      tag: 0.13.0
      pullPolicy: IfNotPresent
    ## Resources for metrics MUST be set when using the high-availability architecture with autoscaling enabled
    ## Otherwise the hpa won't be able to monitor the pod's resources usage
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
